//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmdKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TmdKhoa()
        {
            this.TmdSinhVien = new HashSet<TmdSinhVien>();
        }
    
        public string TmdMaKH { get; set; }
        public string TmdTenKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TmdSinhVien> TmdSinhVien { get; set; }
    }
}
