//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmdMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TmdMonHoc()
        {
            this.TmdKetqua = new HashSet<TmdKetqua>();
        }
    
        public string TmdMaMH { get; set; }
        public string TmdTenMH { get; set; }
        public Nullable<int> TmdSotiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TmdKetqua> TmdKetqua { get; set; }
    }
}
