//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdLesson09.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tmd_qlsinhvienEntities : DbContext
    {
        public tmd_qlsinhvienEntities()
            : base("name=tmd_qlsinhvienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TmdKetqua> TmdKetqua { get; set; }
        public virtual DbSet<TmdKhoa> TmdKhoa { get; set; }
        public virtual DbSet<TmdMonHoc> TmdMonHoc { get; set; }
        public virtual DbSet<TmdSinhVien> TmdSinhVien { get; set; }
    }
}
