//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmdSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TmdSinhVien()
        {
            this.TmdKetqua = new HashSet<TmdKetqua>();
        }
    
        public string TmdMaSV { get; set; }
        public string TmdHoSV { get; set; }
        public string TmdTenSV { get; set; }
        public string TmdPhai { get; set; }
        public Nullable<System.DateTime> TmdNgaySinh { get; set; }
        public string TmdNoiSinh { get; set; }
        public string TmdMaKH { get; set; }
        public Nullable<byte> TmdHocBong { get; set; }
        public Nullable<decimal> TmdDiemTrungBinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TmdKetqua> TmdKetqua { get; set; }
        public virtual TmdKhoa TmdKhoa { get; set; }
    }
}
