//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdK22CNT4Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmdAccount
    {
        public int TmdID { get; set; }
        public string TmdUserName { get; set; }
        public string TmdPassword { get; set; }
        public string TmdFullName { get; set; }
        public string TmdEmail { get; set; }
        public string TmdPhone { get; set; }
        public Nullable<bool> TmdActive { get; set; }
    }
}
