//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdLesson11Db_2210900014.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TmdCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TmdCategory()
        {
            this.TmdProduct = new HashSet<TmdProduct>();
        }
        [Display(Name = "Mã danh mục")]
        public int TmdID { get; set; }
        [Display(Name = "Tên danh mục")]
        public string TmdCateName { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> TmdStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TmdProduct> TmdProduct { get; set; }
    }
}
