//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdLesson11Db_2210900014.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TmdK22CNT4Lesson11DbEntities : DbContext
    {
        public TmdK22CNT4Lesson11DbEntities()
            : base("name=TmdK22CNT4Lesson11DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TmdCategory> TmdCategory { get; set; }
        public virtual DbSet<TmdProduct> TmdProduct { get; set; }
    }
}
