//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdLesson11Db_2210900014.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmdProduct
    {
        public string TmdId2210900014 { get; set; }
        public string TmdProName { get; set; }
        public Nullable<int> TmdQty { get; set; }
        public Nullable<double> TmdPrice { get; set; }
        public Nullable<int> TmdCateId { get; set; }
        public Nullable<bool> TmdActive { get; set; }
    
        public virtual TmdCategory TmdCategory { get; set; }
    }
}
