//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdLesson07Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmdKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmdKhoa()
        {
            this.tmdSinhVien = new HashSet<tmdSinhVien>();
        }
    
        public string TmdKH { get; set; }
        public string TmdTenKH { get; set; }
        public Nullable<bool> TmdTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmdSinhVien> tmdSinhVien { get; set; }
    }
}
