//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdLesson07Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmdSinhVien
    {
        public string TmdMaSV { get; set; }
        public string TmdHoSV { get; set; }
        public string TmdTenSV { get; set; }
        public Nullable<System.DateTime> TmdNgaySinh { get; set; }
        public Nullable<bool> TmdPhai { get; set; }
        public string TmdPhone { get; set; }
        public string TmdEmail { get; set; }
        public string TmdMaKH { get; set; }
    
        public virtual tmdKhoa tmdKhoa { get; set; }
    }
}
