//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdLesson12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmd_Sach
    {
        public string Tmd_MaSach { get; set; }
        public string Tmd_TenSach { get; set; }
        public Nullable<int> Tmd_SoTrang { get; set; }
        public Nullable<System.DateTime> Tmd_NamXB { get; set; }
        public string Tmd_MaTG { get; set; }
        public Nullable<bool> Tmd_TrangThai { get; set; }
    
        public virtual Tmd_TacGia Tmd_TacGia { get; set; }
    }
}
