//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmdLesson12.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TranMinhDuc_2210900014Entities1 : DbContext
    {
        public TranMinhDuc_2210900014Entities1()
            : base("name=TranMinhDuc_2210900014Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tmd_Sach> Tmd_Sach { get; set; }
        public virtual DbSet<Tmd_TacGia> Tmd_TacGia { get; set; }
    }
}
